// 订单
export const TOGGLE_ORDER_SELECTE = "TOGGLE_ORDER_SELECTE";
export const SAVE_ORDER_REDUCER = "SAVE_ORDER_REDUCER";
export const SETREFUNDAMOUNT = 'SETREFUNDAMOUNT'

// 店铺订单搜索
export const FETCH_BCLE_DETAIL_BY_ORDER_ID_AND_MERCHANT_ID = "FETCH_BCLE_DETAIL_BY_ORDER_ID_AND_MERCHANT_ID"
