//店铺
export const SHOP_CHANGE_STATE = "SHOP_CHANGE_STATE";

//运费管理
export const FREIGHT_MANAG_LOADING = "FREIGHT_MANAG_LOADING"; //显示lodaing
export const FREIGHT_MANAG_FIRSTLIST = "FREIGHT_MANAG_FIRSTLIST"; //查询第一页
export const FREIGHT_MANAG_LIST = "FREIGHT_MANAG_LIST"; //非第一页
export const FREIGHT_MANAG_LISTFOOTERnO = "FREIGHT_MANAG_LISTFOOTERnO";
export const FREIGHT_MANAG_REPLACEALL = "FREIGHT_MANAG_REPLACEALL";
export const FREIGHT_MANAG_SHANGLALOADING = "FREIGHT_MANAG_SHANGLALOADING";
export const FETCH_SHOP_ROLELIST = "FETCH_SHOP_ROLELIST";
export const FETCH_SHOP_CHILDREDLIST = "FETCH_SHOP_CHILDREDLIST";

//店铺列表
export const List_FIRSTLOAD = "List_FIRSTLOAD";
export const LIST_LOADMORE = "LIST_LOADMORE";
export const LIST_NO_LOADMORE = "LIST_NO_LOADMORE";
export const LIST_FETCH_LOADINGMORE_SUCCESS = "LIST_FETCH_LOADINGMORE_SUCCESS";
export const LIST_FETCH_NO_LOADINGMORE_SUCCESS =
    "LIST_FETCH_NO_LOADINGMORE_SUCCESS";
export const LIST_FETCH_LOADINGMORE_FAILD = "LIST_FETCH_LOADINGMORE_FAILD";
export const LIST_FETCH_No_LOADINGMORE_FAILD =
    "LIST_FETCH_No_LOADINGMORE_FAILD";

//发票管理
export const CHANGE_STATEDATA = "CHANGE_STATEDATA";