
export const FEATCHMERCHANTLIST = 'FEATCHMERCHANTLIST' // 委派联盟商列表
export const PREJOBDELEGATEDPAGE = 'PREJOBDELEGATEDPAGE' // 已委派 任务委派列表
export const PRECHECKDELEGATEDPAGE = 'PRECHECKDELEGATEDPAGE' // 已委派 验收委派列表
export const PREAUDITDELEGATEDPAGE = 'PREAUDITDELEGATEDPAGE' // 已委派 审核委派列表

export const SAVE_TASK_LIST = "SAVE_TASK_LIST"; // 任务列表页数据
export const SAVE_TASK_HOME_DATA = "SAVE_TASK_HOME_DATA"; // 任务首页数据
export const PREJOBDELEGATINGPAGE = 'PREJOBDELEGATINGPAGE' // 委派 任务委派员工(分店)列表
export const PRECHECKDELEGATINGPAGE = 'PRECHECKDELEGATINGPAGE' // 委派 验收委派员工(分店)列表
export const PREAUDITDELEGATINGPAGE = 'PREAUDITDELEGATINGPAGE' // 委派 审核委派员工(分店)列表

export const UPDATESTAFFLIS = 'UPDATESTAFFLIS' // 更新分店和联盟商列表的信息
export const UPDATEAPPOINTEDLIS = 'UPDATEAPPOINTEDLIS' // 更新分店和联盟商列表的信息
export const UPDATEAPPOINTLIS = 'UPDATEAPPOINTLIS' // 更新分店和联盟商列表的信息
export const UPDATESINGLEAPPOINT = 'UPDATESINGLEAPPOINT' // 更新单个委派员工列表
export const UPDATESINGLEMERCHANTAPPOINT = 'UPDATESINGLEMERCHANTAPPOINT' // 更新单个委派联盟商列表

